{
 "title": "Oracle Errors",
 "tags": [ "Oracle" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dbinstance", "label": "Instance", "query": "oracledb_error" }
  ]
 },
 "panels": [
  {
   "title": "Valid Errors",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "oracledb_error{dbinstance=~'$dbinstance',ignore=\"0\"}"
    }
   ]
  },
  {
   "title": "Ignored Errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "oracledb_error{dbinstance=~'$dbinstance',ignore=\"1\"}"
    }
   ]
  },
  {
   "title": "Altertlog last modified $dbinstance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - avg(oracledb_error_unix_seconds{database!='+ASM',dbinstance=~'$dbinstance'}) without (job)",
     "legendFormat": "{{dbinstance}}"
    }
   ]
  }
 ]
}