{
 "title": "Oracle Overview",
 "description": "oracledb dashboard",
 "tags": [ "Oracle" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "database", "label": "Database", "query": "oracledb_uptime" },
   {
    "name": "dbinstance",
    "label": "Instance",
    "query": "oracledb_uptime{database=\"$database\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime $dbinstance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "repeat": "dbinstance",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(oracledb_uptime{dbinstance=~'$dbinstance'}) without (job)"
    }
   ]
  },
  {
   "title": "FRA Reclaimable",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(oracledb_recovery{database='$database',type=\"percent_space_reclaimable\"})"
    }
   ]
  },
  {
   "title": "Redolog Switches in Last 5 min",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(oracledb_redo{database='$database'})"
    }
   ]
  },
  {
   "title": "FRA Used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "expr": "avg(oracledb_recovery{database='$database',type=\"percent_space_used\"})"
    }
   ]
  },
  {
   "title": "FRA Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(oracledb_recovery{database='$database',type=\"percent_space_used\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(oracledb_recovery{database='$database',type=\"percent_space_reclaimable\"})",
     "legendFormat": "Reclaimable"
    }
   ]
  },
  {
   "title": "Sessions $dbinstance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "repeat": "dbinstance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(oracledb_session{dbinstance=~\"$dbinstance\"}) without (job)",
     "legendFormat": "{{state}} {{type}}"
    }
   ]
  },
  {
   "title": "User Commits / Rollbacks $dbinstance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "repeat": "dbinstance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oracledb_sysstat{dbinstance=~'$dbinstance',type=~'.*commit.*|.*rollback.*'}[10m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Executions / Parses $dbinstance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "repeat": "dbinstance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oracledb_sysstat{dbinstance=~'$dbinstance',type=~'.*count.*'}[10m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio $dbinstance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "repeat": "dbinstance",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(oracledb_cachehitratio{dbinstance=~\"$dbinstance\",type!='cursor_cache_hit_ratio'}) without (job)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cursor Cache Hit Ratio $dbinstance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "repeat": "dbinstance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(oracledb_cachehitratio{dbinstance=~\"$dbinstance\",type='cursor_cache_hit_ratio'}) without (job)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}