{
 "title": "Oracle Transfers RAC",
 "description": "oracledb dashboard",
 "tags": [ "Oracle" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "database", "label": "Database", "query": "oracledb_uptime" },
   {
    "name": "dbinstance",
    "label": "Instance",
    "query": "oracledb_uptime{database=\"$database\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Wait Events $dbinstance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "repeat": "dbinstance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(oracledb_waitclass{dbinstance=~'$dbinstance'}) without (job)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Interconnect  Block Transfer $dbinstance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "repeat": "dbinstance",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(rate(oracledb_interconnect{dbinstance=~'$dbinstance'}[5m])) without (job)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Physical Throughput $dbinstance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "repeat": "dbinstance",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(oracledb_sysmetric{dbinstance=~'$dbinstance',type=~'.*bytes.*'}) without (job)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Physical IOPs $dbinstance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "repeat": "dbinstance",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "avg(oracledb_sysmetric{dbinstance=~'$dbinstance',type=~'.*requests.*'}) without (job)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}