{
 "title": "Oracle Transfers",
 "description": "oracledb dashboard",
 "tags": [ "Oracle" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "database", "label": "Database", "query": "oracledb_uptime" }
  ]
 },
 "panels": [
  {
   "title": "Wait Events $database",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oracledb_waitclass{database='$database'}) without (instance,dbinstance,job)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Interconnect Block Transfer $database",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(sum(rate(oracledb_interconnect{database='$database'}[5m])) without (instance)) without (job)",
     "legendFormat": "{{dbinstance}}:{{type}}"
    }
   ]
  },
  {
   "title": "Physical Throughput $database",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(sum(oracledb_sysmetric{database='$database',type=~'.*bytes.*'}) without (instance,dbinstance)) without (job)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Physical IOPs $database",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "avg(sum(oracledb_sysmetric{database='$database',type=~'.*requests.*'}) without (instance,dbinstance)) without (job)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}